[package]
name = "trowel"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Tools for writing HTML in Rust"
repository = "https://github.com/InsaneWaifu/nakssg"

[dependencies]
trowel_macro = {path = "../trowel_macro", version = "0.1.1"}
