[package]
name = "nakssg"
version = "0.6.1"
edition = "2021"
publish = false

[dependencies]
chrono = "0.4.38"
clap = "4.5.20"
comrak = "0.29.0"
trowel = {path = "trowel"}

[workspace]

members = [
    "trowel_macro", "trowel",
]
